openapi: 3.1.0
info:
  title: Web Crawler API
  description: API to process and extract content from web pages
  version: "1.0.0"
servers:
  - url: https://server_URL:8000
paths:
  /crawl:
    post:
      summary: Process a URL
      description: Receives a URL and its maximum depth to process it and return the content in markdown format
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrawlRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrawlResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    CrawlRequest:
      type: object
      properties:
        url:
          type: string
          format: uri
          example: "https://www.example.com"
        max_depth:
          type: integer
          default: 1
          example: 1
      required:
        - url
    CrawlResponse:
      type: object
      properties:
        status:
          type: string
          example: "success"
        url:
          type: string
          format: uri
          example: "https://www.example.com"
        max_depth:
          type: integer
          example: 1
        content:
          type: string
          example: "Page content in markdown format."
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          example: "Error processing the URL: error description."
